### ISSUE TITLE
Convert to other markdown format for wiki

### ISSUE THREAD

**Issue by Ericson2314** [hsyl20/ghc-cross-compilation#9]
I tried to merge this into the GHC wiki https://gitlab.haskell.org/ghc/ghc/-/wikis/cross-compilation/roadmap

but sadly reST isn't working properly (even though according to the upstream issues it is at least supposed to render right). I suppose the easiest thing to do is just switch to AsciiDoc or Markdown.

**Comment by hsyl20** [comment]
I've converted it manually on the wiki (I've fixed a few things at the same time).
